
FOREWORD

Honesty, justice and courtesy form a moral philosophy
which, associated with mutual interest among men,
constitutes the foundation of ethics.

The electronics and communications engineer
should recognize such a standard,
not in passive observance,
but as a set of dynamic principles
guiding his conduct and way of life.

it is his duty to practice his profession
according to this Code of Ethics and Conduct.




The keystone of professional conduct is integrity.

Hence, it behooves the electronics and communications engineer
to discharge his duty with fidelity
to the public, his employers and clients,
and with fairness and impartiality to all.

It is his duty to interest himself in public welfare
and to be ready to apply his special knowledge
for the benefit of mankind.

He should uphold the honor and dignity of his profession
and avoid the association
with any enterprise of questionable character.

In his dealings with fellow engineers,
he should be fair and tolerant.