                             CONTAINERIZED CARGO




MONTHLY REVENUE                                                 P30,268,794.00

EXPENSES:

     MANPOWER                       10%       P3,026,879.00
     FOL                            3.5%       1,059,408.00
     REPAIR/MAINTENANCE             5%         1,513,449.00
     ADMINISTRATIVE OVERHEAD                   1,520,000.00
     SECURITY                                    200,000.00
     PROFESSIONAL                                250,000.00
     INSURANCE(100M x .008)/12                    67,000.00
     CLAIMS AND DAMAGES             1%           302,688.00
     UTILITIES                      1%           302,688.00
     COMMUNICATIONS                 1%           302,688.00
     MISCELLANEOUS                  1%           302,688.00
     SHARE                                     3,000,000.00
     CONTINGENCIES                             1,500,000.00
     DEPRECIATION(4 YRS.)                      2,084,000.00      15,431,488.00
                                               ------------      -------------
NET INCOME BEFORE INCOME TAX                                    P14,837,306.00
PROVISION FOR INCOME TAX                                          5,193,057.00
                                                                 -------------
NET INCOME FOR THE MONTH                                         P9,644,249.00
                                                                 =============
